server:
  port: 7000

spring:
  # 数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.112.150.204:3306/mall-sale
    driver-class-name: com.mysql.jdbc.Driver
# mybatis设置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
