server:
  port: 7788

spring:
  # 微服务
  cloud:
    nacos:
      # 注册地址
      discovery:
        server-addr:  47.112.150.204:8848
  application:
    name: mall-cart
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 47.112.150.204
    port: 6379
  # 缓存类型
  cache:
    type: redis
    redis:
      # ttl:
      time-to-live: 3600000
  session:
    store-type: redis
thread:
  pool:
    core-size: 20
    max-size: 200
    keep-alive: 10
