server:
  port: 8000

spring:
  # 数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.112.150.204:3306/mall-user
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 47.112.150.204
    port: 6379
  session:
    store-type: redis
  # 微服务
  cloud:
    nacos:
      # 注册地址
      discovery:
        server-addr: 47.112.150.204:8848
  application:
    name: mall-member
# mybatis设置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

feign:
  httpclient:
    connection-timeout: 30000