server:
  port: 8889

spring:
  # 数据源
  # 微服务
  cloud:
    nacos:
      # 注册地址
      discovery:
        server-addr:  47.112.150.204:8848
  redis:
    host: 47.112.150.204
    port: 6379
  session:
    store-type: redis

  application:
    name: mall-search
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false

feign:
  httpclient:
    connection-timeout: 30000