server:
  port: 11000

spring:
  rabbitmq:
    host: 47.112.150.204
    port: 5672
    virtual-host: /
    publisher-returns: true  # 开启发生端消息抵达队列的确认
    template:
      mandatory: true   # 只要抵达队列，以异步发送优先回调我们的 returns
    listener:
      simple:
        acknowledge-mode: manual        # 设置消费者端，手动确认机制
    username: guest
    password: guest

  # 数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.112.150.204:3306/mall-ware
    driver-class-name: com.mysql.jdbc.Driver
  # 微服务
  cloud:
    nacos:
      # 注册地址
      discovery:
        server-addr:  47.112.150.204:8848
#    alibaba:
#      seata:
#        tx-service-group: mall-ware-fescar-service-group
  application:
    name: mall-ware
  # mybatis设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 47.112.150.204
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
