server:
  port: 9000

spring:
  rabbitmq:
    host: 47.112.150.204
    port: 5672
    virtual-host: /
  # 数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.112.150.204:3306/mall-order
    driver-class-name: com.mysql.jdbc.Driver
  # 微服务
  cloud:
    nacos:
      # 注册地址
      discovery:
        server-addr:  47.112.150.204:8848
  application:
    name: mall-order
  # mybatis设置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto